@startuml 07_class

skinparam classAttributeIconSize 0
class 訪問者システム {
 -ユーザID
 -パスワード
 -名前
 -学校名
 -所属名
 -メールアドレス
 -電話番号
 -年齢
 +ユーザID、パスワード、名前、学校名、所属名、メールアドレス、電話番号、年齢を登録する()
 +ユーザID、パスワードを参照する()
 +削除する()
 +更新する()
 +ログインする()
 +ログアウトする()
 ()
}
@enduml